# Generated by Django 4.2.6 on 2023-10-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('post_nom', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('key', models.CharField(max_length=50)),
                ('telephone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('post_nom', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('groupe', models.CharField(max_length=100)),
                ('systeme_de_vote', models.CharField(choices=[('Vote à bulletin sécret', 'Vote A Bulletin Secret'), ('Vote non anonyme', 'Vote Non Anonyme')], default='Vote à bulletin sécret', max_length=100)),
                ('debut_election', models.DateTimeField()),
                ('fin_election', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('resultat', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.election')),
            ],
        ),
        migrations.CreateModel(
            name='VoixVoteSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(null=True)),
                ('key', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.electeur')),
                ('vote_simple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votesimple')),
            ],
        ),
        migrations.CreateModel(
            name='VoixVoteScrutin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.candidat')),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.electeur')),
            ],
        ),
        migrations.CreateModel(
            name='ScrutinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_du_scrutin', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.election')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='list_candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.scrutinlist'),
        ),
    ]
