# Generated by Django 4.2.6 on 2023-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutinlist',
            name='gagnant',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
