# Generated by Django 4.2.6 on 2023-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_scrutinlist_gagnant'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_candidat', verbose_name='photo de profil'),
        ),
    ]
