# Generated by Django 4.2.6 on 2023-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_candidat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutinlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
