# Generated by Django 4.2.6 on 2023-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_scrutinlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='post_nom',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
